openapi: 3.0.0
info:
  title: Gerenciamento de Alunos API
  description: API para gerenciar alunos em uma academia
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /alunos:
    get:
      summary: Lista todos os alunos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aluno'
    post:
      summary: Cria um novo aluno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aluno'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aluno'
  /alunos/{aluno_id}:
    put:
      summary: Atualiza um aluno existente
      parameters:
        - name: aluno_id
          in: path
          required: true
          schema:
            type: integer
          description: ID do aluno a ser atualizado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aluno'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aluno'
        '404':
          description: Aluno não encontrado
    delete:
      summary: Deleta um aluno existente
      parameters:
        - name: aluno_id
          in: path
          required: true
          schema:
            type: integer
          description: ID do aluno a ser deletado
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Aluno deletado com sucesso
        '404':
          description: Aluno não encontrado
components:
  schemas:
    Aluno:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID do aluno
        nome:
          type: string
          description: Nome do aluno
        email:
          type: string
          format: email
          description: E-mail do aluno
      required:
        - nome
        - email
